<Project>
  <PropertyGroup>
    <DSPRecipeTrackerRepositoryRoot>$([MSBuild]::NormalizeDirectory('$(MSBuildThisFileDirectory)'))</DSPRecipeTrackerRepositoryRoot>
    <DSPRecipeTrackerCompileReferenceRoot>$([MSBuild]::NormalizeDirectory('$(DSPRecipeTrackerRepositoryRoot)ci\compile-references'))</DSPRecipeTrackerCompileReferenceRoot>
    <DSPRecipeTrackerSurfaceInventoryPath>$([MSBuild]::NormalizePath('$(DSPRecipeTrackerCompileReferenceRoot)surface-inventory.json'))</DSPRecipeTrackerSurfaceInventoryPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(DSPReferenceMode)' == 'Local' and '$(GameRoot)' != ''">
    <DSPManagedReferenceRoot>$([MSBuild]::NormalizeDirectory('$(GameRoot)\DSPGAME_Data\Managed'))</DSPManagedReferenceRoot>
    <DSPBepInExReferenceRoot>$([MSBuild]::NormalizeDirectory('$(GameRoot)\BepInEx\core'))</DSPBepInExReferenceRoot>
    <DSPAssemblyCSharpReferencePath>$([MSBuild]::NormalizePath('$(DSPManagedReferenceRoot)Assembly-CSharp.dll'))</DSPAssemblyCSharpReferencePath>
    <DSPBepInExReferencePath Condition="'$(BepInExReferencePath)' != ''">$([MSBuild]::NormalizePath('$(BepInExReferencePath)'))</DSPBepInExReferencePath>
    <DSPBepInExReferencePath Condition="'$(DSPBepInExReferencePath)' == ''">$([MSBuild]::NormalizePath('$(DSPBepInExReferenceRoot)BepInEx.dll'))</DSPBepInExReferencePath>
    <DSPUnityEngineReferencePath>$([MSBuild]::NormalizePath('$(DSPManagedReferenceRoot)UnityEngine.dll'))</DSPUnityEngineReferencePath>
    <DSPUnityCoreModuleReferencePath>$([MSBuild]::NormalizePath('$(DSPManagedReferenceRoot)UnityEngine.CoreModule.dll'))</DSPUnityCoreModuleReferencePath>
    <DSPUnityTextRenderingModuleReferencePath>$([MSBuild]::NormalizePath('$(DSPManagedReferenceRoot)UnityEngine.TextRenderingModule.dll'))</DSPUnityTextRenderingModuleReferencePath>
    <DSPUnityUIModuleReferencePath>$([MSBuild]::NormalizePath('$(DSPManagedReferenceRoot)UnityEngine.UIModule.dll'))</DSPUnityUIModuleReferencePath>
    <DSPUnityUIReferencePath>$([MSBuild]::NormalizePath('$(DSPManagedReferenceRoot)UnityEngine.UI.dll'))</DSPUnityUIReferencePath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(DSPReferenceMode)' == 'Hosted' and '$(BepInExReferencePath)' != ''">
    <DSPBepInExReferencePath>$([MSBuild]::NormalizePath('$(BepInExReferencePath)'))</DSPBepInExReferencePath>
    <DSPUnityEngineHostedReferencePath>$([MSBuild]::NormalizePath('$(DSPRecipeTrackerCompileReferenceRoot)Unity.Reference\UnityEngine\obj\Release\netstandard2.0\ref\UnityEngine.dll'))</DSPUnityEngineHostedReferencePath>
    <DSPUnityCoreModuleHostedReferencePath>$([MSBuild]::NormalizePath('$(DSPRecipeTrackerCompileReferenceRoot)Unity.Reference\UnityEngine.CoreModule\obj\Release\netstandard2.0\ref\UnityEngine.CoreModule.dll'))</DSPUnityCoreModuleHostedReferencePath>
    <DSPUnityTextRenderingModuleHostedReferencePath>$([MSBuild]::NormalizePath('$(DSPRecipeTrackerCompileReferenceRoot)Unity.Reference\UnityEngine.TextRenderingModule\obj\Release\netstandard2.0\ref\UnityEngine.TextRenderingModule.dll'))</DSPUnityTextRenderingModuleHostedReferencePath>
    <DSPUnityUIModuleHostedReferencePath>$([MSBuild]::NormalizePath('$(DSPRecipeTrackerCompileReferenceRoot)Unity.Reference\UnityEngine.UIModule\obj\Release\netstandard2.0\ref\UnityEngine.UIModule.dll'))</DSPUnityUIModuleHostedReferencePath>
    <DSPUnityUIHostedReferencePath>$([MSBuild]::NormalizePath('$(DSPRecipeTrackerCompileReferenceRoot)Unity.Reference\UnityEngine.UI\obj\Release\netstandard2.0\ref\UnityEngine.UI.dll'))</DSPUnityUIHostedReferencePath>
    <DSPAssemblyCSharpHostedReferencePath>$([MSBuild]::NormalizePath('$(DSPRecipeTrackerCompileReferenceRoot)DSPGame.Reference\obj\Release\netstandard2.0\ref\Assembly-CSharp.dll'))</DSPAssemblyCSharpHostedReferencePath>
  </PropertyGroup>
</Project>
